name: Auto Update AshStore Repository

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-repository:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update apps.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/update_repo.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git status

          git add apps.json

          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "Auto update app repository"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          fi
