name: Auto Update AshStore Repository

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-repository:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update apps.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/update_repo.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add apps.json

          git diff --cached --quiet || git commit -m "Auto update app repository"

          git push